version: 2
jobs:
  build:
    working_directory: ~/node-web-app
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}

    # In 2.0, we specify our Ruby version by using a public Docker image
    docker:
       - image: circleci/node:7

    steps:
      - checkout

      - setup_remote_docker

      #build image and make two copies
      - run: docker -t build bkauf/node-web-app:${CIRCLE_BUILD_NUM} .
    #  - docker tag ${DTR_IPADDR}/engineering/${DTR_PROJECT}:1.${BUILD_NUMBER} ${DTR_IPADDR}/engineering/${DTR_PROJECT}:latest

    #login to DTR
      - run: docker login -u bkauf -p ${PASSWORD}

    #push both copies of the image
      - run: docker push bkauf/node-web-app:${CIRCLE_BUILD_NUM}





  test:
    working_directory: ~/node-web-app
    docker:
       - image: circleci/node:7

    steps:
      - checkout
      - setup_remote_docker
      - run:
          shell: /bin/bash
          command: |
            #do the env command here

            eval $(<ucp-bundle-admin/env.sh)



            #update/launch service
            if [[ "$(docker service ls --filter name=node-web-app | awk '{print $2}' | grep node-web-app | wc -c)" -ne 0 ]]
            then
              docker service update --image bkauf/node-web-app:${CIRCLE_BUILD_NUM} ${DTR_PROJECT}
            else
              docker service create --replicas 3 -p 8080  --name node-web-app \
              --label com.docker.ucp.mesh.http.80=external_route=http://node-web-app,internal_port=8080 \
              --network ucp-hrm \
              bkauf/node-web-app:${CIRCLE_BUILD_NUM}
            fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
